### ISSUE TITLE
Note on port forwarding in the README

### ISSUE THREAD

**Issue by przemyslawsokol** [vpavkin/ticket-booking-aecor#1]
I think it could be useful to mention that it is needed to cover port forwarding (for ports specified in `docker-compose.yml`) if someone uses `docker-compose` on macOS or Windows, rather than some Linux distribution.

I've got the following setup on my macOS (High Sierra 10.13.6):
```
$ brew list --versions | grep docker
docker 18.09.6
docker-compose 1.24.0
docker-machine 0.16.1
docker-machine-driver-xhyve 0.3.3_1
```

`docker-compose up --detach` works as expected, but containers' ports are not automatically forwarded to the localhost:
```
$ pg_isready -h 127.0.0.1 -p 5432
127.0.0.1:5432 - no response
```

So when trying to run the app (with `sbt booking/run`) we end up with:
```
[error] org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[error]     at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
[error]     at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[error]     at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
(...)
```

All containers that have been started with `docker-compose up --detach` can be reached only via the Docker Machine's IP:
```
$ docker-machine ip default
192.168.64.2
$ pg_isready -h 192.168.64.2 -p 5432
192.168.64.2:5432 - accepting connections
```

To fix the setup one can either alter the `application.conf` values (change `contact-points` to Docker Machine's IP etc.) or forward ports used by ticket-booking-aecor app - either manually via `docker-machine` CLI for SSH or using some tool like [docker-machine-port-forwarder](https://github.com/johanhaleby/docker-machine-port-forwarder):
```
$ pf 5432
$ pf 2181
$ pf 9092
$ pg_isready -h 127.0.0.1 -p 5432
127.0.0.1:5432 - accepting connections
```

I know that `Running` section is not supposed to be a Docker tutorial, but I think it might be helpful if we mention port forwarding requirements in the `README`, in case someone tries to get ticket-booking-aecor running either on macOS or Windows. What do you think @vpavkin?

**Comment by vpavkin** [comment]
@falconepl Thanks for your feedback.
Yep, I'm working on linux so totally missed this thing. I would gladly merge a PR to readme with these notes for devs with MacOs/Win
